language: java
sudo: false
script: mvn clean verify

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT